/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp02.poo;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.MidiEvent;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.Sequence;
import javax.sound.midi.Sequencer;
import javax.sound.midi.ShortMessage;


/**
 *
 * @author Guilherme
 */
public class DualPlayer extends javax.swing.JFrame {
    private Menu menu;
    private int dificuldade, nivelMax, nivelUsuario, nivelJogo, jogador;
    private String nome1, nome2;
    private Resultado resultado;
    List<Integer> listNumber = new ArrayList<>();
    
    public DualPlayer() {
        initComponents();
    }

    public DualPlayer(Menu menu, int dificuldade, String nome1, String nome2){
        this();
        this.menu = menu;
        this.dificuldade = dificuldade;
        this.nome1 = nome1;
        this.nome2 = nome2;
        desativaBotoes();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panicos = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Red = new javax.swing.JButton();
        Green = new javax.swing.JButton();
        Blue = new javax.swing.JButton();
        Yellow = new javax.swing.JButton();
        Exitplays = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        jogadorAtual = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        Panicos.setMaximumSize(new java.awt.Dimension(800, 600));
        Panicos.setMinimumSize(new java.awt.Dimension(800, 600));
        Panicos.setPreferredSize(new java.awt.Dimension(800, 600));
        Panicos.setResizable(false);
        Panicos.getContentPane().setLayout(null);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panicos.getContentPane().add(jButton1);
        jButton1.setBounds(40, 530, 80, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp02/poo/pincher-4449345_1280.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel3.setMinimumSize(new java.awt.Dimension(800, 600));
        Panicos.getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 804, 600);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Genius");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        Red.setBackground(new java.awt.Color(255, 0, 51));
        Red.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        Red.setText("W");
        Red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedActionPerformed(evt);
            }
        });
        Red.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RedKeyPressed(evt);
            }
        });
        jPanel1.add(Red);
        Red.setBounds(95, 75, 300, 200);

        Green.setBackground(new java.awt.Color(0, 204, 51));
        Green.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        Green.setText("E");
        Green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenActionPerformed(evt);
            }
        });
        Green.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GreenKeyPressed(evt);
            }
        });
        jPanel1.add(Green);
        Green.setBounds(413, 75, 300, 200);

        Blue.setBackground(new java.awt.Color(0, 102, 255));
        Blue.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        Blue.setText("S");
        Blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueActionPerformed(evt);
            }
        });
        Blue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BlueKeyPressed(evt);
            }
        });
        jPanel1.add(Blue);
        Blue.setBounds(95, 287, 300, 200);

        Yellow.setBackground(new java.awt.Color(255, 255, 0));
        Yellow.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        Yellow.setText("D");
        Yellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YellowActionPerformed(evt);
            }
        });
        Yellow.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                YellowKeyPressed(evt);
            }
        });
        jPanel1.add(Yellow);
        Yellow.setBounds(413, 287, 300, 200);

        Exitplays.setText("Sair");
        Exitplays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitplaysActionPerformed(evt);
            }
        });
        Exitplays.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ExitplaysKeyPressed(evt);
            }
        });
        jPanel1.add(Exitplays);
        Exitplays.setBounds(615, 513, 98, 44);

        btnStart.setText("Começar");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart);
        btnStart.setBounds(472, 513, 98, 44);

        jogadorAtual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jogadorAtual);
        jogadorAtual.setBounds(95, 513, 186, 44);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(720, 520, 50, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 806, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void RedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedActionPerformed
        acaoVermelho();
        funcaoJogar(3);
    }//GEN-LAST:event_RedActionPerformed

    private void YellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YellowActionPerformed
        acaoAmarelo();
        funcaoJogar(4);
    }//GEN-LAST:event_YellowActionPerformed

    private void BlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueActionPerformed
        acaoAzul();
        funcaoJogar(2);
    }//GEN-LAST:event_BlueActionPerformed

    private void ExitplaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitplaysActionPerformed
        this.setEnabled(false);
        this.setVisible(false);
        
        menu.setEnabled(true);
        menu.setVisible(true);
    }//GEN-LAST:event_ExitplaysActionPerformed

    private void GreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenActionPerformed
        acaoVerde();
        funcaoJogar(1);
    }//GEN-LAST:event_GreenActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        ativaBotoes();
        btnStart.setVisible(false);
        jogarPvp();
    }//GEN-LAST:event_btnStartActionPerformed

    private void RedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RedKeyPressed
        this.playWithKey(evt); 
    }//GEN-LAST:event_RedKeyPressed

    private void BlueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BlueKeyPressed
        this.playWithKey(evt); 
    }//GEN-LAST:event_BlueKeyPressed

    private void YellowKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YellowKeyPressed
        this.playWithKey(evt); 
    }//GEN-LAST:event_YellowKeyPressed

    private void GreenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GreenKeyPressed
        this.playWithKey(evt); 
    }//GEN-LAST:event_GreenKeyPressed

    private void ExitplaysKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ExitplaysKeyPressed
        this.playWithKey(evt); 
    }//GEN-LAST:event_ExitplaysKeyPressed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jPanel1.setVisible(false);
        Panicos.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel1.setVisible(true);
        Panicos.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void finaliza(int i){
        this.setEnabled(false);
        this.setVisible(false);
        
        menu.setEnabled(true);
        menu.setVisible(true);
        
        switch(i){
            case 0 -> resultado = new Resultado(nome1, 1);
            case 1 -> resultado = new Resultado(nome2, 1);
            case 2 -> resultado = new Resultado(nome1, nome2);
            }
    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DualPlayer().setVisible(true);
            }
        });
    }
    
    private void jogarPvp(){//Função responsável pela Inicialização do jogo
        jogadorAtual.setText(nome1+", Sua vez:");
        nivelJogo = 0;
        nivelUsuario = 0; //Iniciando as variaveis como para iniciar o jogo
        jogador = 0;
        switch(this.dificuldade){//switch para relacionar a dificuldade com o nivel maximo de cada uma
                case 1 -> nivelMax = 8;
                case 2 -> nivelMax = 14;
                case 3 -> nivelMax = 20;
                case 4 -> nivelMax = 31;
                case 5 -> nivelMax = -1;//Foi utilizado o -1 para modo infinito pois como a variavel comparativa incrementa pra cima, nunca vai ter critério de parada
            }
    }
    
    private void funcaoJogar(int valor){//Função responsavel pelo fluxo do jogo
        if(jogador == 0){                       //Tratamento diferente para cada jogador
            if(nivelJogo == nivelUsuario){      //caso o usuario tenha digitado a sequencia toda
                adicionarJogada(valor);         //Adiciona o novo valor
                nivelUsuario = 0;               //volta para a iteração 0
                jogador++;                      //passa para o próximo jogador
                jogadorAtual.setText(nome2+", Sua vez:");
            }else{
                switch(verificaJogada(valor)){  
                    case 1 -> nivelUsuario++;   //caso o usuario tenha acertado, passa para a próxima incrementação
                    case 0 -> finaliza(1); //caso o usuario tenha errado
                }
            }
        }else{
            if(verificaJogada(valor) == 0){
                finaliza(0);
            }else if(verificaJogada(valor) == 1){
                if(nivelJogo == nivelUsuario){
                    nivelJogo++;
                    nivelUsuario = 0;
                    //caso de empate
                    if(nivelJogo == nivelMax){
                        finaliza(2);
                        return;
                    }
                    jogador--;
                    jogadorAtual.setText(nome1+", Sua vez:");
                }else{
                    nivelUsuario++;
                }
            }
        }
    }
    
    private void playWithKey(java.awt.event.KeyEvent evt)//Função responsável pela utilização do teclado
    {
        char keyPressed = evt.getKeyChar();
        funcaoJogar(getColorFromKey(keyPressed));
    }
    
    private int getColorFromKey(char key){//Função de conversão das teclas em valores
        if(key == 'w' || key == 'W'){ //vermelho
           acaoVermelho();
           return 3;
        }
        
        if(key == 'e' || key == 'E'){ //verde
            acaoVerde();
            return 1;
        }
        
        if(key == 's' || key == 'S'){ //azul
            acaoAzul();
            return 2;
        }
        
        if(key == 'd' || key == 'D'){ //amarelo
            acaoAmarelo();
            return 4;
        }
        return -1;
        
    }
    private int verificaJogada(int valor){
        //compara se os valores são iguais
        if(listNumber.get(nivelUsuario) != valor){
            return 0;
        }
        return 1;
    }
    
    private void adicionarJogada(int valor){//Adiciona jogada ao fim do vetor
        listNumber.add(valor); 
    }    
    
    private void sleepTime(int temp) {//Função responsável por pausar o tempo
        try{
            Thread.sleep(temp);
        } catch (InterruptedException xs) {
            Logger.getLogger(SinglePlayer.class.getName()).log(Level.SEVERE, null, xs);
        } 
    }
    
    private void acaoVerde(){   //Função responsável pela ação da cor verde
        //implementar as açoes do botão 
        //Audio
        //Luz
        Runnable r = new Runnable() {
            @Override
            public void run() {
                for(int i = 1; i < 256; i += 1) {
                    Green.setBackground(new Color(i, 255 - i, 255 - 1));
                    repaint();
                    sleepTime(1);
                }
                Green.setBackground(Color.green);
            }
        };
        playPiano(65);
        Thread t = new Thread(r);
        t.start();
    }
    
    private void acaoAzul(){//Função responsável pela ação da cor Azul
        Runnable r = new Runnable() {
            @Override
            public void run() {            
                for(int i = 1; i < 256; i += 1) {
                    Blue.setBackground(new Color(i, 255 - i, 255 - 1));
                    repaint();
                    sleepTime(1);
                }
                Blue.setBackground(Color.blue);
            }
        };
        playPiano(70);
        Thread t = new Thread(r);
        t.start();
        //implementar as açoes do botão 
        //Audio
        //Luz
    }
    
    private void acaoVermelho(){//Função responsável pela ação da cor Vermelha
        Runnable r = new Runnable() {
            @Override
            public void run() {               
                for(int i = 1; i < 256; i += 1) {
                    Red.setBackground(new Color(i, 255 - i, 255 - 1));
                    repaint();
                    sleepTime(1);                  
                }
                Red.setBackground(Color.red);
            }
        };
        playPiano(60);
        Thread t = new Thread(r);
        t.start();
        
        //implementar as açoes do botão 
        //Audio
        //Luz
    }
    
    private void acaoAmarelo(){//Função responsável pela ação da Amarela
        Runnable r = new Runnable() {
            @Override
            public void run() {             
                for(int i = 1; i < 256; i += 1) {
                    Yellow.setBackground(new Color(i, 255 - i, 255 - 1));
                    repaint();
                    sleepTime(1);
                }
                Yellow.setBackground(Color.yellow);
            }
        };
        playPiano(80);
        Thread t = new Thread(r);
        t.start();
    }
    
    public void playPiano(int note){
        if(note < 1){
            note = 1;
        }
        else if(note > 100){
            note = 100;
        }

        // Try block to check for exceptions
        try {
            // Getting a sequencer and open it
            Sequencer player = MidiSystem.getSequencer();
            player.open();
 
            // Making 1a new Sequence
            Sequence seq = new Sequence(Sequence.PPQ, 128);
 
            // Creating a new track
            javax.sound.midi.Track track = seq.createTrack();
 
            // Making a Message
            ShortMessage a = new ShortMessage();
 
            // Put the Instruction in the Message
            a.setMessage(144, 1, note, 100);
 
            // Make a new MidiEvent
            MidiEvent noteOn = new MidiEvent(a, 2);
 
            // Add MidiEvent to the Track
            track.add(noteOn);
 
            // Giving sequence to Sequencer
            player.setSequence(seq);
 
            // Start the Sequencer using start() method
            player.start();
        }
 
        // Catch block to handle exceptions
        catch (Exception ex) {
            // Display the exception on console
            // along with line number
            ex.printStackTrace();
        }
    }
    
    private void desativaBotoes(){//Função responsável pela desativação dos botões
        Green.setEnabled(false);
        Red.setEnabled(false);
        Yellow.setEnabled(false);
        Blue.setEnabled(false);
    }
    
    private void ativaBotoes(){//Função responsável pela Ativação dos botões
        Green.setEnabled(true);
        Red.setEnabled(true);
        Yellow.setEnabled(true);
        Blue.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blue;
    private javax.swing.JButton Exitplays;
    private javax.swing.JButton Green;
    private javax.swing.JFrame Panicos;
    private javax.swing.JButton Red;
    private javax.swing.JButton Yellow;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jogadorAtual;
    // End of variables declaration//GEN-END:variables
}
